import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import {ClerkProvider} from '@clerk/nextjs'
import {dark} from "@clerk/themes";
import styles from "@/app/index.module.css";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
      }}
    >
      <html lang="en" suppressHydrationWarning>
      <body className={GeistSans.className}>
      <main className={styles.main}>
        {children}
      </main>
      </body>
      </html>
    </ClerkProvider>

  );
}
